services:
  prometheus:
    build: prometheus
    restart: always

  grafana:
    build: grafana
    ports:
      - "127.0.0.1:18034:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    restart: always

  exporter:
    build: exporter
    restart: always
