global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'time-tracking-dashboard-exporter'
    static_configs:
      - targets: ['exporter:3000']
