{
 "title": "Uptime",
 "tags": [ "example" ],
 "templating": {
  "list": [
   { "name": "secondinhours", "query": "3600" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "timestamp(up)", "legendFormat": "__auto" },
    {
     "expr": " timestamp(up offset -$__interval)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ttd_disk_free_gb{}", "legendFormat": "Free" },
    { "expr": "ttd_disk_used_gb{}", "legendFormat": "Used" }
   ]
  },
  {
   "title": "Memory",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ttd_memory_free_mb{}", "legendFormat": "Free" },
    { "expr": "ttd_memory_used_mb{}", "legendFormat": "Used" }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "timestamp(up)", "legendFormat": "__auto" },
    {
     "expr": " timestamp(up offset -$__interval)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "ttd_cpu_current_load_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "ttd_memory_used_percent{}", "legendFormat": "__auto" }
   ]
  }
 ]
}